import Head from 'next/head'
import Game from '../src/Game'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Tap word</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Game />
    </div>
  )
}
